const urls = {
  terms: "/terms",
  pricing: "/pricing",
  blog: "/blog",
  privacy: "/privacy",
  libraries: "https://github.com/trycourier",
  getStarted: "/",
  apiReference: "https://docs.courier.com/reference",
  status: "https://status.courier.com/",
  disclosure: "/disclosure",
  subprocessors: "/subprocessors",
  documentation: "https://docs.courier.com/docs",
  about: "/about",
  careers: "https://jobs.lever.co/trycourier",
  github: "https://www.github.com/trycourier",
  twitter: "https://www.twitter.com/trycourier",
  linkedin: "https://www.linkedin.com/company/trycourier",
  facebook: "https://www.facebook.com/trycourier",
  instagram: "https://www.instagram.com/trycourier",
  youtube: "https://www.youtube.com/channel/UCuONBIOzl-hypZ5qqWKDeeg",
  providers: "/providers",
  help: "https://help.courier.com/en/",
  twitch: "https://www.twitch.tv/trycourier",
  discord: "https://discord.com/invite/courier",
  updates: "https://updates.courier.com/",
  login: "https://app.courier.com/login",
  signup: "https://app.courier.com/signup",
  requestDemo: "/request-demo",
  developersGuideNotifications: "/developers-guide-notifications",
  security: "https://security.courier.com",
  googleOauth:
    "https://courier.auth.us-east-1.amazoncognito.com/oauth2/authorize?identity_provider=Google&redirect_uri=https://app.courier.com/login/callback&response_type=CODE&client_id=5f4fmec2qnuscp89qbt8nsuftj&scope=aws.cognito.signin.user.admin%20email%20openid%20profile",
  email_providers: "https://docs.courier.com/docs/email-integrations",
  lists: "https://docs.courier.com/docs/lists",
};

export let {
  terms,
  pricing,
  blog,
  privacy,
  libraries,
  getStarted,
  disclosure,
  subprocessors,
  documentation,
  about,
  careers,
  github,
  twitter,
  linkedin,
  facebook,
  instagram,
  youtube,
  twitch,
  discord,
  status,
  help,
  updates,
  apiReference,
  providers,
  login,
  signup,
  requestDemo,
  developersGuideNotifications,
  security,
  googleOauth,
  email_providers,
} = urls;
