const urls = {
  terms: "/terms",
  pricing: "/pricing",
  blog: "/blog",
  privacy: "/privacy",
  libraries: "https://github.com/trycourier",
  getStarted: "/",
  status: "https://status.courier.com/",
  disclosure: "/disclosure",
  subprocessors: "/subprocessors",
  docs: "/docs",
  docsApiReference: "/docs/reference",
  docsTutorials: "/docs/guides/tutorials/how-to-design-a-notification-template",
  docsLibraries: "/docs/#client-libraries",
  docsProviders: "/docs/guides/providers/",
  about: "/about",
  careers: "https://jobs.lever.co/trycourier",
  github: "https://www.github.com/trycourier",
  twitter: "https://www.twitter.com/trycourier",
  linkedin: "https://www.linkedin.com/company/trycourier",
  facebook: "https://www.facebook.com/trycourier",
  instagram: "https://www.instagram.com/trycourier",
  youtube: "https://www.youtube.com/channel/UCuONBIOzl-hypZ5qqWKDeeg",
  providers: "/providers",
  help: "https://help.courier.com/en/",
  twitch: "https://www.twitch.tv/trycourier",
  discord: "https://discord.com/invite/courier",
  updates: "https://updates.courier.com/",
  login: "https://app.courier.com/login",
  signup: "https://app.courier.com/signup",
  requestDemo: "/request-demo",
  developersGuideNotifications: "/guides/user-notification-system",
  security: "https://security.courier.com",
  googleOauth:
    "https://courier.auth.us-east-1.amazoncognito.com/oauth2/authorize?identity_provider=Google&redirect_uri=https://app.courier.com/login/callback&response_type=CODE&client_id=5f4fmec2qnuscp89qbt8nsuftj&scope=aws.cognito.signin.user.admin%20email%20openid%20profile",
  email_providers: "/docs/guides/providers/email",
  featuresTemplates: "/features/templates",
  featuresRouting: "/features/routing-engine",
  featuresProfiles: "/features/preferences",
  featuresAutomations: "/features/automations",
  useCaseTransactional: "/transactional-notifications",
  useCaseUserActivity: "/user-activity-notifications",
  useCaseAlert: "/alert-notifications",
  useCaseAction: "/action-notifications",
  enterprise: "/enterprise",
};

export let {
  terms,
  pricing,
  blog,
  privacy,
  libraries,
  getStarted,
  disclosure,
  subprocessors,
  docs,
  docsApiReference,
  docsTutorials,
  docsLibraries,
  docsProviders,
  about,
  careers,
  github,
  twitter,
  linkedin,
  facebook,
  instagram,
  youtube,
  twitch,
  discord,
  status,
  help,
  updates,
  providers,
  login,
  signup,
  requestDemo,
  developersGuideNotifications,
  security,
  googleOauth,
  email_providers,
  featuresTemplates,
  featuresRouting,
  featuresProfiles,
  featuresAutomations,
  useCaseTransactional,
  useCaseUserActivity,
  useCaseAlert,
  useCaseAction,
  enterprise,
} = urls;
